# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ae39e432a28db5d44023cc6f0fea6d91f94db37292393844cf9c69bfd5992d904c0404ae208741167539d27768c767c17d18b2c7bd3c63a9272486736b8da98

test:
  secret_key_base: e939cc4b465b6987625dc07e0226a1e5e97f70f72114110d02af402efdbca22e4b05e842e7111d262f7bb37710f5f3e9b9b39b9ee513530baeb3996eba6e21eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
